# Generated by Django 4.1 on 2022-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=150)),
                ('project_technology', models.CharField(max_length=150)),
                ('project_description', models.TextField(blank=True)),
                ('project_othertechnology', models.TextField(blank=True)),
                ('project_image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
