# Generated by Django 4.1 on 2022-11-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_project_othertechnology_projects_project_other_technology_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
