# Generated by Django 4.1 on 2022-11-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
