# Generated by Django 4.1 on 2022-11-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_technology_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technology_name',
        ),
    ]
