# Generated by Django 4.1 on 2022-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_project_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.IntegerField(choices=[(0, 'JavaScript'), (1, 'Java'), (2, 'Python'), (3, 'Android'), (4, 'Apple'), (5, 'Other')], default=6),
        ),
    ]
